# Generated by Django 4.2.2 on 2023-07-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('img', models.CharField(max_length=700)),
                ('bio', models.TextField(max_length=3000)),
                ('verified_actor', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=700)),
                ('title', models.CharField(max_length=3000)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('runtime', models.IntegerField(default=0)),
                ('genre', models.CharField(max_length=3000)),
                ('synopsis', models.CharField(max_length=3000)),
                ('actors', models.ManyToManyField(related_name='movies', to='main_app.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=3000)),
                ('movies', models.ManyToManyField(to='main_app.movie')),
            ],
        ),
    ]
