# Generated by Django 4.2.2 on 2023-07-02 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=700)),
                ('title', models.CharField(max_length=3000)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('runtime', models.IntegerField(default=0)),
                ('genre', models.CharField(max_length=3000)),
                ('synopsis', models.CharField(max_length=3000)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='main_app.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=3000)),
                ('movies', models.ManyToManyField(to='main_app.movie')),
            ],
        ),
    ]
